name: Frontend CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-build:
    name: Lint & Build
    runs-on: ubuntu-latest
    continue-on-error: true    # ✅ Do not block deployment if this fails

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install Dependencies
      run: npm ci

    - name: Lint Code
      run: npm run lint

    - name: Build Frontend
      run: npm run build

  deploy:
    if: github.ref == 'refs/heads/main'
    name: Deploy Frontend to EC2
    runs-on: ubuntu-latest
    needs: lint-and-build       # Wait for lint, but don't block if it fails

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install Dependencies
      run: npm ci

    - name: Build Frontend
      run: npm run build

    - name: Save EC2 SSH Key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Clear /var/www/html before upload
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "rm -rf ${{ secrets.NGINX_HTML_DIR }}/*"

    - name: Upload dist/ to EC2 /var/www/html/
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no -i key.pem" dist/ \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.NGINX_HTML_DIR }}/
